apiVersion: v1
kind: Pod
metadata:
  name: {{.Release.Name}}-spring-demo
  labels:
    version: {{.Chart.Version}}
    app: spring-demo
    release: {{.Release.Name}}
spec:
  containers:
    - image: harbor.ellin.net/library/spring-demo:{{.Release.Version}}
      name: spring-demo
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-spring-demo-service
  labels:
    app: spring-demo
    version: {{.Chart.Version}}
    release: {{.Release.Name}}
    
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: spring-demo  
    version: {{.Chart.Version}}
    release: {{.Release.Name}}
