apiVersion: v1
kind: Pod
metadata:
  name: spring-demo
spec:
  containers:
    - image: harbor.ellin.net/library/spring-demo
      name: spring-demo
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
