apiVersion: v1
kind: Pod
metadata:
  name: spring-demo
  labels:
    version: "ok"
    app: spring-demo
spec:
  containers:
    - image: ellinj/spring-demo
      name: spring-demo
      imagePullPolicy: Always
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
