apiVersion: v1
kind: Pod
metadata:
  name: spring-demo
  labels:
    version: "{VERSION}"
    app: spring-demo
spec:
  containers:
    - image: ellinj/spring-demo
      name: spring-demo
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: spring-demo-service
  labels:
    app: spring-demo
    version: "{VERSION}"
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: spring-demo  
