kind: Service
apiVersion: v1
metadata:
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/actuator/prometheus'
    prometheus.io/port: 8080
  name:  spring-demo-web
spec:
  selector:
    app:  spring-demo
  type:  LoadBalancer  
  ports:
  - name: http
    port:  80
    targetPort:  8080