resources:
- name: release
  type: s3
  source:
    bucket: releases
    access_key_id: minio
    secret_access_key: minio123
    endpoint: http://minio.ellin.net
    regexp: release-(.*).tgz
- name: version
  type: semver
  source:
    driver: git
    uri: git@github.com:jeffellin/spring-demo.git
    branch: version
    file: version
    private_key: ((private_key))
- name: source-code
  type: git
  source:
    uri: git@github.com:jeffellin/spring-demo.git
    branch: master
    private_key: ((private_key))
- name: docker-image
  type: docker-image
  source:
    repository: harbor.ellin.net:443/library/spring-demo
    username: jeff
    password: Pivotal!23
    insecure_registries:
      - harbor.ellin.net:443
jobs:
  - name: build-project
    serial: true
    plan:
      - get: source-code
        trigger: true
      - get: version
        params: {bump: minor}
      - task: build-project
        file: source-code/ci/tasks/maven-build-task.yml
      - put: release
        params:
          file: packed-release/release-*.tgz
  - name: deploy-image
    plan:
      - get: release
        passed: [build-project]
        trigger: true
      - task: push-to-docker
        config:
          inputs:
          - name: release
          outputs:
          - name: docker-build
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: busybox}
          run:
            path: sh
            args: 
              - -exc
              - |
                ls
                ls release
                tar xvf release/release-0.0.1.tgz -C docker-build
      - put: docker-image
        params:
          build: docker-build
  - name: push-to-pks
    plan:
      - get: release
        passed: [deploy-image]
        trigger: true
      - get: source-code
      - task: push-to-pks
        file: source-code/ci/tasks/pks-deploy-task.yml
        vars:
          PKS_USER: ((PKS_USER))
          PKS_PASSWORD: ((PKS_PASSWORD))
          PKS_ENDPOINT: ((PKS_ENDPOINT))
          PKS_CLUSTER: ((PKS_CLUSTER))