resources:
- name: version
  type: semver
  source:
    driver: git
    uri: git@github.com:jeffellin/spring-demo.git
    branch: version
    file: version
    private_key: ((private_key))
- name: source-code
  type: git
  source:
    uri: git@github.com:jeffellin/spring-demo.git
    branch: master
    private_key: ((private_key))
- name: source-code-gitops
  type: git
  source:
    uri: git@github.com:jeffellin/spring-demo-gitops.git
    branch: master
    private_key: ((private_key))    
- name: docker-image
  type: docker-image
  source:
    repository: ellinj/spring-demo
    username: ((docker.email))
    password: ((docker.password))
jobs:
  - name: build-project
    serial: true
    plan:
      - get: source-code
        trigger: true
      - get: source-code-gitops
      - get: version
        params: {bump: minor}
      - task: build-project
        file: source-code/ci/tasks/maven-build-task.yml
      - task: simpletask
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: alpine/git
          run:
            path: sh
            args:
              - -exc
              - |
                ls -la
                VERSION=$(cat version/version)
                cp -r source-code-gitops/. gitops
                sed -r  "s/^(\s*)(newTag\s*:.*$)/\1newTag: \"${VERSION}\"/" gitops/kubernetes/kustomization.yaml
                sed -r -i "s/^(\s*)(newTag\s*:.*$)/\1newTag: \"${VERSION}\"/" gitops/kubernetes/kustomization.yaml
          inputs:
          - name: source-code-gitops
          - name: version
          outputs:
          - name: gitops
      - put: version
        params: {file: version/version}
      - put: source-code-gitops 
        params: 
          repository: gitops
      - put: docker-image
        params:
          build: packed-release/target
          tag_file: version/version
          tag_as_latest: true
