resources:
- name: release
  type: s3
  source:
    bucket: releases
    access_key_id: minio
    secret_access_key: minio123
    skip_ssl_verification: true
    endpoint: http://minio.ellin.net
- name: source-code
  type: git
  source:
    uri: git@github.com:jeffellin/spring-demo.git
    branch: master
    private_key: ((private_key))
- name: docker-image
  type: docker-image
  source:
    repository: harbor.ellin.net:443/library/spring-demo
    username: jeff
    password: Pivotal!23
    insecure_registries:
      - harbor.ellin.net:443
jobs:
  - name: job-bump-date
    serial: true
    plan:
      - get: source-code
      - task: build-project
        file: source-code/ci/tasks/maven-build-task.yml
      - put: release
        params:
          file: packed-release/release-*.tgz
  - name: deploy-image
    plan:
      - get: docker-image
      - task: hello-world
        config:
            platform: linux
            image_resource:
              type: docker-image
              source: {repository: busybox}
            run:
              path: echo
              args: [hello world]
      - put: docker-image
        params:
          build: source-code/targe